name: syn_menu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  multiselect: ^0.0.7
  flutter:
    sdk: flutter
  get: ^4.6.5
  multi_select_flutter: ^4.1.3
  google_nav_bar: ^5.0.6
  getwidget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - assets/images/logo.png

# open your terminal then write following commands
#flutter clean
#flutter pub get
# flutter run

